language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t jpf4e/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true jpf4e/react-test npm test

after_success:
        - docker build -t jpf4e/multi-client ./client
        - docker build -t jpf4e/multi-nginx ./nginx
        - docker build -t jpf4e/multi-server ./server
        - docker build -t jpf4e/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push jpf4e/multi-client
        - docker push jpf4e/multi-nginx
        - docker push jpf4e/multi-server
        - docker push jpf4e/multi-worker
